credentials:
  usernames:
    Booggii:
      email: booggii@email.com
      name: Booggii
      password: $2b$12$65.bca6xULpfbM1C1hyiU.MEjGzg7zT0n1x6QRO6gRVj4kiIrm5ai # encrypted version of "Booggii2024"
cookie:
  expiry_days: 0
  key: signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
    - melsby@gmail.com
